### ISSUE TITLE
Teams Error Message: Can't show this content

### ISSUE THREAD

**Issue by mscherotter** [davrous/metaverseliveshare#1]
I've followed the instructions to set this up and have run into a problem.

1. I created a new Developer Tenant for Teams 
2. I followed the instructions to successfully add the MetaverseLiveShare app to a meeting in the developer tenant
3. The museum scene shows up in Teams on the developer tenant system when I add it to a meeting.
4. I invite my @microsoft.com to the meeting and join the meeting.
5. I Press Share to Stage from the developer account Teams user
6. On the @microsoft.com account, I see this error message in the Teams meeting whenever I press the "Share to Stage" button in the developer account.  Can't show this content, something went wrong.

Is a developer preview of Teams needed for this to work?

I have also tried with the second account being one of the fictitious user accounts created for the developer account and get the same results.

![image](https://user-images.githubusercontent.com/641702/215278690-7e60d156-098a-411b-a2ca-d3396629261a.png)

Any suggestions?

**Comment by davrous** [comment]
We've been discussing this issue offlline. You need to enable the Developer Preview mode of MS Teams: https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro to make it work. I've updated the readme. Thanks for the feedback!
